pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: rake docker:create_deployment ip=imjac.in
- script: rake docker:build
- script: docker login -u $(dockerUsername) -p $(dPasswd)
  env:
    dPasswd: $(dockerPassword)
    dUser: $(dockerUsername)
- script: rake docker:push
- script: rake docker:deploy