version: '3'
services:
  # Migrate DB in development
  setup:
    build: .
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
    command: "bin/rails db:migrate"
  # Database
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=imjacinta_development
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
  # DB Viewer (pgadmin)
  db_pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: "none"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user
      - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - "3080:80"
  # Webapp
  web:
    build: .
    image: imjacinta
    command: bundle exec rails s -p 3333 -b 0.0.0.0
    volumes:
      - .:/imjacinta
    ports:
      - "3333:3333"
    depends_on:
      - db
volumes:
  pgdata:
