apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    metdata:
      name: migrate
    spec:
      containers:
      - name: migrate
        image: jaci/imjacinta:latest
        args: ["rake db:create && rake db::migrate"]
        envFrom:
        - configMapRef:
            name: rails-config
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-user
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user
              key: password
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: "secret-key-base"
              key: "secret-key-base"