apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: imjacinta
spec:
  ports:
    - port: 5432
  selector:
    app: imjacinta
    tier: db

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-vol
  labels:
    type: local
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: imjacinta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imjacinta
      tier: db
  template:
    metadata:
      name: db
      labels:
        app: imjacinta
        tier: db
    spec:
      volumes:
      - name: db-vol
        persistentVolumeClaim:
          claimName: db-volclaim
      containers:
      - name: db
        image: postgres:9.6-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-user
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: rails-config
              key: DATABASE_NAME
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: db-vol