global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'imjacinta'
    metrics_path: '/internal/metrics'
    static_configs:
    - targets: ['imjacinta:3000']
  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['traefik:8080']