logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[traefikLog]
  filePath = "/acme/traefik.log"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[docker]
  watch = true
  swarmMode = true

[etcd]
endpoint = "etcd:2379"
prefix = "/traefik"

[acme]
email = "jaci.brunning@gmail.com"
entryPoint = "https"
onHostRule = true
storage = "/acme/acme.json"

[acme.httpChallenge]
entryPoint = 'http'

[metrics]
  [metrics.prometheus]
    entryPoint = 'traefik'